[package]
name = "efx-attrnames"
version = "0.1.0"
edition = "2024"
publish = false
rust-version = "1.85"
license = "MIT OR Apache-2.0"

[lib]
proc-macro = true

[dependencies]
quote = "1.0"
proc-macro2 = "1.0"
syn = { version = "2.0", features = ["full"] }
