[package]
name = "efx-sandbox"
version = "0.1.0"
edition = "2024"
rust-version = "1.85"
publish = false

[dependencies]
eframe = "0.32"
efx       = { path = "../efx" }
efx-core  = { path = "../efx-core" }
