name: Clippy

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  clippy:
    name: Run Clippy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy
      - uses: Swatinem/rust-cache@v2

      - name: Install Linux dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            g++ pkg-config libx11-dev libasound2-dev libudev-dev \
            libxkbcommon-x11-0 libwayland-dev libxkbcommon-dev \
            libxcb-render0-dev libxcb-shape0-dev libxcb-xfixes0-dev

      - name: Run Clippy
        run: cargo clippy --all-targets --all-features -- -D warnings